version: '3.7'
services:
  web:
    image: nginx:latest
    container_name: "krzysztof-moskalik-web"
    expose:
      - 80
    links:
      - php
    environment:
      - VIRTUAL_HOST=krzysztof-moskalik.pl
      - LETSENCRYPT_HOST=krzysztof-moskalik.pl
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7-fpm
    container_name: "krzysztof-moskalik-php"
    volumes:
      - ./:/var/www
      
  composer:
    image: composer:latest
    container_name: "krzysztof-moskalik-composer"
    command: ["composer", "install"]
    volumes:
      - ./:/app

networks:
  default:
    external:
      name: nginx-proxy
