version: '3.9'

services:
  app:
    build:
      target: app-prod
      dockerfile: Dockerfile
    image: webdevops/php-nginx:8.2
    expose:
      - "80"
    volumes:
      - ./public:/app/public:cached
      - ./src:/app/src:cached
    restart: unless-stopped