version: '3.9'

services:
  app:
    build:
      target: app-prod
      dockerfile: Dockerfile
    image: webdevops/php-nginx:8.2
    ports:
      - "8080:80"
    volumes:
      - ./public:/app/public:cached
      - ./src:/app/src:cached   # optional, if you have other PHP code
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_DISPLAY_ERRORS=1
      - VIRTUAL_HOST=krzysztof-moskalik.pl
      - LETSENCRYPT_HOST=krzysztof-moskalik.pl
    restart: unless-stopped